### ISSUE TITLE
Add dates

### ISSUE THREAD

**Issue by ericearl** [nimh-dsst/lunch-and-learn#3]
It would be good to add dates to the presentations and discussions as well as who hosted/presented/facilitated.

**Comment by joshlawrimore** [comment]
@ericearl , I probably should have had you review this prior to closing the PR... which also closed this issue 😞 . Please reopen if you want me to make changes...

**Comment by joshlawrimore** [comment]
@ericearl let me know if you want me to alter anything else. Thanks!

**Comment by ericearl** [comment]
While we remember, we should add in the names to give credit for hosting, presenting, and facilitating.
